# Generated by Django 5.0.6 on 2024-06-29 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fruta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("classificacao", models.CharField(max_length=100)),
                ("fresca", models.BooleanField(default=True)),
                ("qtd_estoque", models.IntegerField()),
                ("preco", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=50)),
                ("is_admin", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vendas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qtd_vendida", models.IntegerField()),
                ("data_venda", models.DateTimeField(auto_now_add=True)),
                (
                    "fruta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="frutaria.fruta"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="frutaria.user"
                    ),
                ),
            ],
        ),
    ]
