# Generated by Django 5.0.4 on 2024-07-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='user',
        ),
        migrations.AddField(
            model_name='vendas',
            name='vendedor_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
