# Generated by Django 5.0.4 on 2024-07-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutaria', '0002_remove_vendas_user_vendas_vendedor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendas',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
