# Generated by Django 5.0.4 on 2024-07-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutaria', '0003_vendas_valor_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='valor_venda',
            field=models.FloatField(),
        ),
    ]
