# Generated by Django 5.0.4 on 2024-07-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutaria', '0004_alter_vendas_valor_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruta',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='valor_venda',
            field=models.FloatField(default=0.0),
        ),
    ]
