# Generated by Django 5.0.4 on 2024-07-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutaria', '0006_classificacao_remove_fruta_classificacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruta',
            name='classificacoes',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='estoque',
            name='fruta',
        ),
        migrations.AddField(
            model_name='fruta',
            name='classificacao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruta',
            name='qtd_estoque',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Classificacao',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
    ]
