# Generated by Django 5.0.4 on 2024-07-08 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutaria', '0007_remove_fruta_classificacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruta',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='fruta',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='fruta',
            name='qtd_estoque',
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(max_length=100)),
                ('qtd_estoque', models.IntegerField()),
                ('preco', models.FloatField(default=0.0)),
                ('id_fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frutaria.fruta')),
            ],
        ),
    ]
