# Generated by Django 5.0.4 on 2024-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutaria', '0008_remove_fruta_classificacao_remove_fruta_preco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruta',
            name='classificacao',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fruta',
            name='preco',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fruta',
            name='qtd_estoque',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Classificacao',
        ),
    ]
